version: '3.8'
services:
  backend:
    build:
      context: ./backend
    environment:
      DB_NAME: home_zone_analyzer
      DB_USER: postgres
      DB_PASSWORD: V!ttori0123
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: home_zone_analyzer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: V!ttori0123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
