apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: vittoriorossetto/backend:latest
        ports:
        - containerPort: 9000
        env:
        - name: DB_NAME
          value: home_zone_analyzer
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: V!ttori0123
        - name: DB_HOST
          value: db
        - name: DB_PORT
          value: "5432"

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30001
  selector:
    app: backend
