apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: vittoriorossetto/frontend:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
    - port: 3000   # Internal port exposed by the service
      targetPort: 3000  # Port on the pods the service forwards traffic to
      nodePort: 30002  # NodePort you are using
  selector:
    app: frontend  # Selector matching your frontend pods
